const express = require('express')
const Route = express.Router()
const movieRouter = require('../modules/movie/movie_routes')
const ruanganRouter = require('../modules/dataPeminjam/dataPeminjam_routes')
const premiereRouter = require('../modules/premiere/premiere_routes')
const showTimeRouter = require('../modules/show_time/show_time_routes')
const bookingRouter = require('../modules/booking/booking_routes')
const authRouter = require('../modules/auth/auth_routes')
const userRouter = require('../modules/user/user_routes')
const bookingRuanganRouter = require('../modules/bookingRuangan/bookingRuangan_routes')
const laporanRuanganRouter = require('../modules/laporanRuangan/laporanRuangan_routes')
const waitingListRouter = require('../modules/waitingList/waitingList_routes')

Route.use('/waitinglist', waitingListRouter)
Route.use('/ruangan', ruanganRouter)
Route.use('/bookingruangan', bookingRuanganRouter)
Route.use('/movie', movieRouter)
Route.use('/premiere', premiereRouter)
Route.use('/show_time', showTimeRouter)
Route.use('/booking', bookingRouter)
Route.use('/user', userRouter)
Route.use('/auth', authRouter)
Route.use('/laporanruangan', laporanRuanganRouter)
module.exports = Route
